### ISSUE TITLE
huohukey

### ISSUE THREAD

**Issue by Miaomiaofeng** [ros/solidworks_urdf_exporter#157] opened 2024-05-14 02:30 UTC
**What versions of the installer have you tried?**

**Have you confirmed that installing by source is successful?**

**What version of SolidWorks and SP?**

**Comment by brawner** [comment] 2024-05-14 18:26
Duplicate of https://github.com/ros/solidworks_urdf_exporter/issues/150

**Closed by brawner** 2024-05-14 18:26 UTC
Labels: Update Installer
