### ISSUE TITLE
URDF file exported from SW2018 has a problem in Moveit!

### ISSUE THREAD

**Issue by 13651924886** [ros/solidworks_urdf_exporter#70] opened 2019-06-25 04:56 UTC
I exported urdf files from Solidworks2018 through the solidworks_urdf_exporter, the model is mainly about a 6-axis robot arm which I wanna use it with Moveit! to accomplish motion planning. But I got a problem when I use the Moveit! setup assistant. The Joint cannot be moved,kinda like locked when i set up the pose. But in rviz(roslaunch myrobot display.launch), joint state publisher works pretty well  because i can drag the block to set the joint angle value in the GUI and the joint of the robot moves simultaneously.
![Screenshot from 2019-06-25 13-04-43](https://user-images.githubusercontent.com/39672603/60070740-5622b500-974a-11e9-9f3f-e049b0537c2c.png)
![Screenshot from 2019-06-25 13-06-08](https://user-images.githubusercontent.com/39672603/60070741-56bb4b80-974a-11e9-99e5-609b42a7d05b.png)

As you can see ,the joint GUI in second Screenshot cannot be moved when I drag them. And I'm pretty sure that I set the planning group correctly(Chain from Base_Link to Link6)

**Comment by brawner** [comment] 2019-08-01 22:32
If this works fine with the joint state publisher, then I'm not sure what the MoveIt issue is. Maybe @davetcoleman has some ideas

**Comment by cesic** [comment] 2019-08-09 11:16
I have the same question

**Comment by davetcoleman** [comment] 2019-08-13 19:13
I'm not sure what would cause that except if your joint value range was zero, or maybe really really small.. ?

Seems like a question for the https://github.com/ros-planning/moveit repo instead of here.

Btw the logic for those sliders is here:
https://github.com/ros-planning/moveit/blob/master/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp#L477

Feel free to debug yourself and suggest a PR ;-)

**Comment by caioaamaral** [comment] 2020-01-23 02:19
does your URDF have transmission tags?

**Comment by brawner** [comment] 2020-06-12 04:00
Closing due to age. It also doesn't seem like the issue is with this code.

**Closed by brawner** 2020-06-12 04:00 UTC
Labels: help wanted
